<script>
import FormField from '@/components/core/FormField'

export default {
  name: 'SelectCountry',
  extends: FormField,
  props: {
    type: {
      default: 'select',
      type: String,
    },
  },
  beforeMount () {
    this.selectOptions = [
      { value: 'ABW', name: 'Aruba' },
      { value: 'AFG', name: 'Afghanistan' },
      { value: 'AGO', name: 'Angola' },
      { value: 'AIA', name: 'Anguilla' },
      { value: 'ALB', name: 'Albania' },
      { value: 'AND', name: 'Andorra' },
      { value: 'ANT', name: 'Netherlands Antilles' },
      { value: 'ARE', name: 'United Arab Emirates' },
      { value: 'ARG', name: 'Argentina' },
      { value: 'ARM', name: 'Armenia' },
      { value: 'ASM', name: 'American Samoa' },
      { value: 'ATA', name: 'Antarctica' },
      { value: 'ATF', name: 'French Southern territories' },
      { value: 'ATG', name: 'Antigua and Barbuda' },
      { value: 'AUS', name: 'Australia' },
      { value: 'AUT', name: 'Austria' },
      { value: 'AZE', name: 'Azerbaijan' },
      { value: 'BDI', name: 'Burundi' },
      { value: 'BEL', name: 'Belgium' },
      { value: 'BEN', name: 'Benin' },
      { value: 'BFA', name: 'Burkina Faso' },
      { value: 'BGD', name: 'Bangladesh' },
      { value: 'BGR', name: 'Bulgaria' },
      { value: 'BHR', name: 'Bahrain' },
      { value: 'BHS', name: 'Bahamas' },
      { value: 'BIH', name: 'Bosnia and Herzegovina' },
      { value: 'BLR', name: 'Belarus' },
      { value: 'BLZ', name: 'Belize' },
      { value: 'BMU', name: 'Bermuda' },
      { value: 'BOL', name: 'Bolivia' },
      { value: 'BRA', name: 'Brazil' },
      { value: 'BRB', name: 'Barbados' },
      { value: 'BRN', name: 'Brunei' },
      { value: 'BTN', name: 'Bhutan' },
      { value: 'BVT', name: 'Bouvet Island' },
      { value: 'BWA', name: 'Botswana' },
      { value: 'CAF', name: 'Central African Republic' },
      { value: 'CAN', name: 'Canada' },
      { value: 'CCK', name: 'Cocos (Keeling) Islands' },
      { value: 'CHE', name: 'Switzerland' },
      { value: 'CHL', name: 'Chile' },
      { value: 'CHN', name: 'China' },
      { value: 'CIV', name: 'Côte dIvoire' },
      { value: 'CMR', name: 'Cameroon' },
      { value: 'COD', name: 'Congo, The Democratic Republic of the' },
      { value: 'COG', name: 'Congo' },
      { value: 'COK', name: 'Cook Islands' },
      { value: 'COL', name: 'Colombia' },
      { value: 'COM', name: 'Comoros' },
      { value: 'CPV', name: 'Cape Verde' },
      { value: 'CRI', name: 'Costa Rica' },
      { value: 'CUB', name: 'Cuba' },
      { value: 'CXR', name: 'Christmas Island' },
      { value: 'CYM', name: 'Cayman Islands' },
      { value: 'CYP', name: 'Cyprus' },
      { value: 'CZE', name: 'Czech Republic' },
      { value: 'DEU', name: 'Germany' },
      { value: 'DJI', name: 'Djibouti' },
      { value: 'DMA', name: 'Dominica' },
      { value: 'DNK', name: 'Denmark' },
      { value: 'DOM', name: 'Dominican Republic' },
      { value: 'DZA', name: 'Algeria' },
      { value: 'ECU', name: 'Ecuador' },
      { value: 'EGY', name: 'Egypt' },
      { value: 'ERI', name: 'Eritrea' },
      { value: 'ESH', name: 'Western Sahara' },
      { value: 'ESP', name: 'Spain' },
      { value: 'EST', name: 'Estonia' },
      { value: 'ETH', name: 'Ethiopia' },
      { value: 'FIN', name: 'Finland' },
      { value: 'FJI', name: 'Fiji Islands' },
      { value: 'FLK', name: 'Falkland Islands' },
      { value: 'FRA', name: 'France' },
      { value: 'FRO', name: 'Faroe Islands' },
      { value: 'FSM', name: 'Micronesia, Federated States of' },
      { value: 'GAB', name: 'Gabon' },
      { value: 'GBR', name: 'United Kingdom' },
      { value: 'GEO', name: 'Georgia' },
      { value: 'GHA', name: 'Ghana' },
      { value: 'GIB', name: 'Gibraltar' },
      { value: 'GIN', name: 'Guinea' },
      { value: 'GLP', name: 'Guadeloupe' },
      { value: 'GMB', name: 'Gambia' },
      { value: 'GNB', name: 'Guinea-Bissau' },
      { value: 'GNQ', name: 'Equatorial Guinea' },
      { value: 'GRC', name: 'Greece' },
      { value: 'GRD', name: 'Grenada' },
      { value: 'GRL', name: 'Greenland' },
      { value: 'GTM', name: 'Guatemala' },
      { value: 'GUF', name: 'French Guiana' },
      { value: 'GUM', name: 'Guam' },
      { value: 'GUY', name: 'Guyana' },
      { value: 'HKG', name: 'Hong Kong' },
      { value: 'HMD', name: 'Heard Island and McDonald Islands' },
      { value: 'HND', name: 'Honduras' },
      { value: 'HRV', name: 'Croatia' },
      { value: 'HTI', name: 'Haiti' },
      { value: 'HUN', name: 'Hungary' },
      { value: 'IDN', name: 'Indonesia' },
      { value: 'IND', name: 'India' },
      { value: 'IOT', name: 'British Indian Ocean Territory' },
      { value: 'IRL', name: 'Ireland' },
      { value: 'IRN', name: 'Iran' },
      { value: 'IRQ', name: 'Iraq' },
      { value: 'ISL', name: 'Iceland' },
      { value: 'ISR', name: 'Israel' },
      { value: 'ITA', name: 'Italy' },
      { value: 'JAM', name: 'Jamaica' },
      { value: 'JOR', name: 'Jordan' },
      { value: 'JPN', name: 'Japan' },
      { value: 'KAZ', name: 'Kazakstan' },
      { value: 'KEN', name: 'Kenya' },
      { value: 'KGZ', name: 'Kyrgyzstan' },
      { value: 'KHM', name: 'Cambodia' },
      { value: 'KIR', name: 'Kiribati' },
      { value: 'KNA', name: 'Saint Kitts and Nevis' },
      { value: 'KOR', name: 'South Korea' },
      { value: 'KWT', name: 'Kuwait' },
      { value: 'LAO', name: 'Laos' },
      { value: 'LBN', name: 'Lebanon' },
      { value: 'LBR', name: 'Liberia' },
      { value: 'LBY', name: 'Libyan Arab Jamahiriya' },
      { value: 'LCA', name: 'Saint Lucia' },
      { value: 'LIE', name: 'Liechtenstein' },
      { value: 'LKA', name: 'Sri Lanka' },
      { value: 'LSO', name: 'Lesotho' },
      { value: 'LTU', name: 'Lithuania' },
      { value: 'LUX', name: 'Luxembourg' },
      { value: 'LVA', name: 'Latvia' },
      { value: 'MAC', name: 'Macao' },
      { value: 'MAR', name: 'Morocco' },
      { value: 'MCO', name: 'Monaco' },
      { value: 'MDA', name: 'Moldova' },
      { value: 'MDG', name: 'Madagascar' },
      { value: 'MDV', name: 'Maldives' },
      { value: 'MEX', name: 'Mexico' },
      { value: 'MHL', name: 'Marshall Islands' },
      { value: 'MKD', name: 'Macedonia' },
      { value: 'MLI', name: 'Mali' },
      { value: 'MLT', name: 'Malta' },
      { value: 'MMR', name: 'Myanmar' },
      { value: 'MNG', name: 'Mongolia' },
      { value: 'MNP', name: 'Northern Mariana Islands' },
      { value: 'MOZ', name: 'Mozambique' },
      { value: 'MRT', name: 'Mauritania' },
      { value: 'MSR', name: 'Montserrat' },
      { value: 'MTQ', name: 'Martinique' },
      { value: 'MUS', name: 'Mauritius' },
      { value: 'MWI', name: 'Malawi' },
      { value: 'MYS', name: 'Malaysia' },
      { value: 'MYT', name: 'Mayotte' },
      { value: 'NAM', name: 'Namibia' },
      { value: 'NCL', name: 'New Caledonia' },
      { value: 'NER', name: 'Niger' },
      { value: 'NFK', name: 'Norfolk Island' },
      { value: 'NGA', name: 'Nigeria' },
      { value: 'NIC', name: 'Nicaragua' },
      { value: 'NIU', name: 'Niue' },
      { value: 'NLD', name: 'Netherlands' },
      { value: 'NOR', name: 'Norway' },
      { value: 'NPL', name: 'Nepal' },
      { value: 'NRU', name: 'Nauru' },
      { value: 'NZL', name: 'New Zealand' },
      { value: 'OMN', name: 'Oman' },
      { value: 'PAK', name: 'Pakistan' },
      { value: 'PAN', name: 'Panama' },
      { value: 'PCN', name: 'Pitcairn' },
      { value: 'PER', name: 'Peru' },
      { value: 'PHL', name: 'Philippines' },
      { value: 'PLW', name: 'Palau' },
      { value: 'PNG', name: 'Papua New Guinea' },
      { value: 'POL', name: 'Poland' },
      { value: 'PRI', name: 'Puerto Rico' },
      { value: 'PRK', name: 'North Korea' },
      { value: 'PRT', name: 'Portugal' },
      { value: 'PRY', name: 'Paraguay' },
      { value: 'PSE', name: 'Palestine' },
      { value: 'PYF', name: 'French Polynesia' },
      { value: 'QAT', name: 'Qatar' },
      { value: 'REU', name: 'Réunion' },
      { value: 'ROM', name: 'Romania' },
      { value: 'RUS', name: 'Russian Federation' },
      { value: 'RWA', name: 'Rwanda' },
      { value: 'SAU', name: 'Saudi Arabia' },
      { value: 'SDN', name: 'Sudan' },
      { value: 'SEN', name: 'Senegal' },
      { value: 'SGP', name: 'Singapore' },
      { value: 'SGS', name: 'South Georgia and the South Sandwich Islands' },
      { value: 'SHN', name: 'Saint Helena' },
      { value: 'SJM', name: 'Svalbard and Jan Mayen' },
      { value: 'SLB', name: 'Solomon Islands' },
      { value: 'SLE', name: 'Sierra Leone' },
      { value: 'SLV', name: 'El Salvador' },
      { value: 'SMR', name: 'San Marino' },
      { value: 'SOM', name: 'Somalia' },
      { value: 'SPM', name: 'Saint Pierre and Miquelon' },
      { value: 'SRB', name: 'Serbia' },
      { value: 'STP', name: 'Sao Tome and Principe' },
      { value: 'SUR', name: 'Suriname' },
      { value: 'SVK', name: 'Slovakia' },
      { value: 'SVN', name: 'Slovenia' },
      { value: 'SWE', name: 'Sweden' },
      { value: 'SWZ', name: 'Swaziland' },
      { value: 'SYC', name: 'Seychelles' },
      { value: 'SYR', name: 'Syria' },
      { value: 'TCA', name: 'Turks and Caicos Islands' },
      { value: 'TCD', name: 'Chad' },
      { value: 'TGO', name: 'Togo' },
      { value: 'THA', name: 'Thailand' },
      { value: 'TJK', name: 'Tajikistan' },
      { value: 'TKL', name: 'Tokelau' },
      { value: 'TKM', name: 'Turkmenistan' },
      { value: 'TMP', name: 'East Timor' },
      { value: 'TON', name: 'Tonga' },
      { value: 'TTO', name: 'Trinidad and Tobago' },
      { value: 'TUN', name: 'Tunisia' },
      { value: 'TUR', name: 'Turkey' },
      { value: 'TUV', name: 'Tuvalu' },
      { value: 'TWN', name: 'Taiwan' },
      { value: 'TZA', name: 'Tanzania' },
      { value: 'UGA', name: 'Uganda' },
      { value: 'UKR', name: 'Ukraine' },
      { value: 'UMI', name: 'United States Minor Outlying Islands' },
      { value: 'URY', name: 'Uruguay' },
      { value: 'USA', name: 'United States' },
      { value: 'UZB', name: 'Uzbekistan' },
      { value: 'VAT', name: 'Holy See (Vatican City State)' },
      { value: 'VCT', name: 'Saint Vincent and the Grenadines' },
      { value: 'VEN', name: 'Venezuela' },
      { value: 'VGB', name: 'Virgin Islands, British' },
      { value: 'VIR', name: 'Virgin Islands, U.S.' },
      { value: 'VNM', name: 'Vietnam' },
      { value: 'VUT', name: 'Vanuatu' },
      { value: 'WLF', name: 'Wallis and Futuna' },
      { value: 'WSM', name: 'Samoa' },
      { value: 'YEM', name: 'Yemen' },
      { value: 'YUG', name: 'Yugoslavia' },
      { value: 'ZAF', name: 'South Africa' },
      { value: 'ZMB', name: 'Zambia' },
      { value: 'ZWE', name: 'Zimbabwe' },
    ]
  },
}
</script>

<style lang="stylus">
// .SelectCountry
</style>
